version: '3'

services:
    kafka:
        image: docker.io/bitnami/kafka:latest
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        ports:
             - "2181:2181"

    jobmanager:
        image: flink:latest
        container_name: jobmanager
        ports:
            - "8081:8081"
        command: jobmanager
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
    taskmanager:
        image: flink:latest
        depends_on:
            - jobmanager
        command: taskmanager
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                taskmanager.numberOfTaskSlots: 2